from user_logic_interpretor.derrive_logic.syntax import key_word_syntax, syntax_dic
from user_logic_interpretor.derrive_logic.convert_logic import convert_logic
from user_logic_interpretor.derrive_logic.common import *